language: ruby
cache: bundler
rvm:
- 2.4.0

script:
  - ./setup.sh
# disable rake for now as our builds are unstable anyways
#  - bundle exec rake test

branches:
  only:
  - master
  - /dev-(.*)/

sudo: false
