# world.ac Jekyll Config File.
# Careful messing with this if you don't know what it means! Find out more at jekyllrb.com
# Last Major Release: 2.0.0

# General Site Build Settings
title: World Affairs Conference
description: The WAC website!
baseurl: ""
url: "world.ac"
github: "https://github.com/malsf21/world.ac"

# Social Accounts
email: mailto:wac@ucc.on.ca
facebook: https://www.facebook.com/worldaffairsconference/
instagram: "https://instagram.com/WorldAffairsCon"
twitter: https://twitter.com/WorldAffairsCon

# Build Settings
markdown: kramdown
exclude: [vendor]

# Rendered Collections
collections:
  plenaries:
    output: true
    layout: plenary

# Excludes
exclude:
  - ".travis.yml"
  - README.md
  - "*.sh"
