# Site settings
title: World Affairs Conference
email: wac@ucc.on.ca
description: The WAC website!
baseurl: "/wac"
url: "world.ac"
blogurl: "/wac/blog"
twitter_username: WorldAffairsCon
github_username:  malsf21

# Build settings
markdown: kramdown

collections:
  plenaries:
    output: true
    layout: plenary
