# Site settings
title: World Affairs Conference
email: wac@ucc.on.ca
description: The WAC website!
baseurl: "/wactest"
url: "world.ac"
github: "https://github.com/malsf21/world.ac"

# Social

email: mailto:wac@ucc.on.ca
facebook: https://www.facebook.com/worldaffairsconference/
instagram: "#"
twitter: https://twitter.com/WorldAffairsCon

# Build settings
markdown: kramdown
exclude: [vendor]

collections:
  plenaries:
    output: true
    layout: plenary
