# Site settings
title: World Affairs Conference
email: wac@ucc.on.ca
description: The WAC website!
baseurl: "/wac"
url: "world.ac"
lead_web_dev: Jack Sarick
twitter_username: WorldAffairsCon
github_username:  malsf21

# Build settings
markdown: kramdown

collections:
<<<<<<< HEAD
  
=======
  speakers:
    output: true
    layout: speaker
>>>>>>> master
  plenaries:
    output: true
    layout: plenary